export const IS_CREATING_EXPENSE = 'IS_CREATING_EXPENSE';
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING';
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILED="REGISTER_FAILED";
export const GET_ALL_ERRORS = 'GET_ALL_ERRORS';
export const CLEAR_ERRORS="CLEAR_ERRORS";

